db:
  image: postgres
  volumes:
    - /var/lib/postgresql
web:
  build: .
  command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000" # kind of janky to wait for db...
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
